import { useEffect, useState, useRef } from 'react'
import Head from 'next/head'
import html2canvas from 'html2canvas'
import styles from '../styles/Home.module.css'
import { Button } from 'react-bootstrap';
// import { Ico } from 'bootstrap-icon';
// <i className="bi bi-arrow-down-circle-fill"></i>
// 
// npm i bootstrap-icons

export default function Home() {
  const [user, setUser] = useState("Mamerto");
  const printRef = useRef();
  const [colorLetter, setColorLetter] = useState(["#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc", "#f6a403ad", "#154293b3", "#eb1f26b8", "#2ea137b8", "#ab529bcc",])

  const handleDownloadImage = async () => {
    const element = document.getElementById('print'),
      canvas = await html2canvas(element),
      data = canvas.toDataURL('image/jpg'),
      link = document.createElement('a');

    link.href = data;
    link.download = `${user}-potencia-de-vida-by-minota.png`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadImageT3 = async () => {
    const element = document.getElementById('print3'),
      canvas = await html2canvas(element),
      data = canvas.toDataURL('image/jpg'),
      link = document.createElement('a');

    link.href = data;
    link.download = `${user}-potencia-de-vida-by-minota.png`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadImageT4 = async () => {
    const element = document.getElementById('print4'),
      canvas = await html2canvas(element),
      data = canvas.toDataURL('image/jpg'),
      link = document.createElement('a');

    link.href = data;
    link.download = `${user}-potencia-de-vida-by-minota.png`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadImageT5 = async () => {
    const element = document.getElementById('print5'),
      canvas = await html2canvas(element),
      data = canvas.toDataURL('image/jpg'),
      link = document.createElement('a');

    link.href = data;
    link.download = `${user}-potencia-de-vida-by-minota.png`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadImageT6 = async () => {
    const element = document.getElementById('print6'),
      canvas = await html2canvas(element),
      data = canvas.toDataURL('image/jpg'),
      link = document.createElement('a');

    link.href = data;
    link.download = `${user}-potencia-de-vida-by-minota.png`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadImageFlayer = async () => {
    const element = document.getElementById('print2'),
      canvas = await html2canvas(element),
      data = canvas.toDataURL('image/jpg'),
      link = document.createElement('a');

    link.href = data;
    link.download = `${user}-potencia-de-vida-by-minota.png`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const dtnDonwload = (fnc, opc) => {
    return <Button onClick={fnc} variant="outline-primary"
      style={{ width: opc && "100%" }}
    >
      <i className="bi bi-chevron-down ico-download" ></i>
      Descargar
    </Button>
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Pensamos en todos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="msapplication-TileImage" content="favicon.png" />
        <style type="text/css" id="wp-custom-css"></style>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <a
          style={{ textDecoration: "none" }}
          href="https://www.facebook.com/Jordanminota/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h5
            style={{fontFamily: "monospace", fontSize: "15px"}}
            className="my-0 mr-md-auto font-weight-normal"
          >Con ❤️ by Jordan Minota</h5>
        </a>
          
        </div>

        <div className="pricing-header px-auto py-auto pt-md-auto pb-md-auto mx-auto text-center">

          <h1 className={styles.title} style={{ color: "#929292", fontSize: "50px" }}>
            #VivirSabroso
          </h1>

          <div className="container">
            <div className="row text-center">
              <div className="col-lg-4 col-md-3 col-sm-3 text-center">

              </div>
              <div className="col-lg-4 col-md-6 col-sm-6 text-center">

              </div>
              <div className="col-lg-4 col-md-3 col-sm-3 text-center">

              </div>
            </div>
          </div>


          <div className="typewriter">
            <input
              autoFocus
              placeholder='Escribe tu nombre!'
              style={{width: "300px"}}
              autoComplete="off"
              onClick={() => setUser('.')}
              className='inp'
              name="Name"
              onChange={(e) => setUser(e.target.value)}
            />
          </div>

          <div className='mx-auto'>
            <img src="/Logo-Pactowhite-1.png" alt="me" style={{
              top: "20px!important",
              width: "100px",
              position: "relative",
              left: "0px",
              filter: "opacity(0.8)"
            }} />

          </div>

        </div>


        <div className="container">
          <div className="row text-center">
            <div className="card-deck col-lg-6 col-md-6 col-sm-12">
              <div className="card shadow p-3 mb-5 bg-white rounded">
                <div className="card-body">
                  <div id="print" style={{ paddingBottom: "100px", paddingTop: "100px" }}>
                    <div className='basic'>
                      <h1 className={styles.title} style={{ display: "inline", fontSize: "50px" }}>
                        {
                          user.split('').map((letter, index) => {
                            return <p key={index} style={{ color: (letter === " ") ? "#ffffff00" : colorLetter[index], display: "inline" }}>
                              {
                                (letter === " ") ? <span styles={{ color: "#ffffff00" }}> - </span> : letter.toUpperCase()
                              }
                            </p>
                          })
                        }
                      </h1>
                      <img src="/palomita.png" alt="me" width="30" height="30" style={{
                        top: "-20px!important",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                    </div>
                    <center>
                      <img src="/name.png" alt="me" style={{
                        width: "200px",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                    </center>
                  </div>

                  {dtnDonwload(handleDownloadImage)}




                </div>
              </div>

            </div>
            <div className="card-deck col-lg-6 col-md-6 col-sm-12">
              <div className="card shadow p-3 mb-5 bg-white rounded">
                <div className="card-body">
                  <div id="print3" style={{ padding: "30px" }}>
                    <div className='basic'>
                      <img src="/t3/p3-1.png" alt="me" width="300" style={{
                        top: "-20px!important",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                      <br></br>

                      <h1 className={styles.title} style={{ display: "inline", fontSize: "50px" }}>
                        {
                          user.split('').map((letter, index) => {
                            return <p key={index} style={{ color: (letter === " ") ? "#ffffff00" : colorLetter[index], display: "inline" }}>
                              {
                                (letter === " ") ? <span styles={{ color: "#ffffff00" }}> - </span> : letter.toUpperCase()
                              }
                            </p>
                          })
                        }
                      </h1>
                      <br></br>

                    </div>
                    <center>
                      <img src="/t3/p3-2.png" alt="me" width="300" style={{
                        top: "0px!important",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                    </center>
                  </div>

                  {dtnDonwload(handleDownloadImageT3)}

                </div>
              </div>

            </div>




            <div className="card-deck col-lg-6 col-md-6 col-sm-12">
              <div className="card shadow p-3 mb-5 bg-white rounded">
                <div className="card-body">
                  <div id="print4" style={{ padding: "80px" }}>
                    <div className='basic'>

                      <h1 className={styles.title} style={{ display: "inline-block", marginBottom: "30px", fontSize: "50px" }}>
                        {
                          user.split('').map((letter, index) => {
                            return <p key={index} style={{ color: (letter === " ") ? "#ffffff00" : colorLetter[index], display: "inline" }}>
                              {
                                (letter === " ") ? <span styles={{ color: "#ffffff00" }}> - </span> : letter.toUpperCase()
                              }
                            </p>
                          })
                        }
                      </h1>
                      <img src="/palomita.png" alt="me" width="30" height="30" style={{
                        top: "-20px!important",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                    </div>
                    <center>
                      <img src="/t4/p4-2.png" alt="me" style={{
                        width: "250px",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                    </center>
                  </div>

                  {dtnDonwload(handleDownloadImageT4)}

                </div>
              </div>

            </div>






            <div className="card-deck col-lg-6 col-md-6 col-sm-12 ">
              <div className="card shadow p-3 mb-5 bg-white rounded">
                <div className="card-body">
                  <div id="print5" style={{ paddingTop: "15px", paddingBottom: "15px" }}>
                    <div className='basic'>
                      <img src="/t5/p5-1.png" alt="me" width="400" style={{
                        top: "-20px!important",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                      <br></br>

                      <h1 className={styles.title} style={{ display: "inline", fontSize: "40px" }}>
                        {
                          user.split('').map((letter, index) => {
                            return <p key={index} style={{ color: (letter === " ") ? "#ffffff00" : colorLetter[index], display: "inline" }}>
                              {
                                (letter === " ") ? <span styles={{ color: "#ffffff00" }}> - </span> : letter.toUpperCase()
                              }
                            </p>
                          })
                        }
                      </h1>
                      <br></br>

                    </div>
                    <center>
                      <img src="/t5/p5-2.png" alt="me" width="400" style={{
                        top: "0px!important",
                        position: "relative",
                        left: "0px",
                        filter: "opacity(0.8)"
                      }} />
                    </center>
                  </div>

                  {dtnDonwload(handleDownloadImageT5)}


                </div>
              </div>

            </div>




            <div className="col-lg-3 col-md-3 col-sm-12">
            </div>
            <div className="col-lg-6 col-md-12 col-sm-12">



              <div className="card-deck">
                <div className="card shadow p-3 mb-5 bg-white rounded justify-content-md-center">
                  <div className="card-body">
                    <div id="print5">
                      <div className='basic'>

                        <div id="print6" style={{ padding: "80px" }}>
                          <div className='basic'>
                            <img src="/t6/p6-1.png" alt="me" width="400" style={{
                              top: "-20px!important",
                              position: "relative",
                              left: "0px",
                              filter: "opacity(0.8)"
                            }} />
                            <br></br>

                            <h1 className={styles.title} style={{ display: "inline", fontSize: "50px" }}>
                              {
                                user.split('').map((letter, index) => {
                                  return <p key={index} style={{ color: (letter === " ") ? "#ffffff00" : colorLetter[index], display: "inline" }}>
                                    {
                                      (letter === " ") ? <span styles={{ color: "#ffffff00" }}> - </span> : letter.toUpperCase()
                                    }
                                  </p>
                                })
                              }
                            </h1>
                            <br></br>

                          </div>
                          <center>
                            <img src="/t6/p6-2.png" alt="me" width="400" style={{
                              top: "0px!important",
                              position: "relative",
                              left: "0px",
                              filter: "opacity(0.8)"
                            }} />
                          </center>
                        </div>

                        {dtnDonwload(handleDownloadImageT6)}
                      </div>
                    </div>
                  </div>
                </div>
              </div>


            </div>
            <div className="col-lg-3 col-md-3 col-sm-12">
            </div>
          </div>
        </div>

      </main>

      <main className={styles.main}>


        <div className='sombra' style={{
          boxShadow: "0px 0px 20px -6px rgba(0,0,0,0.47)!important",
          borderRadius: "5px",
          width: "",
        }}>

          <div className='basic2' id="print2" style={{ width: "200" }}>
            <img src="/t2/1.png" alt="me" width="400" style={{
              position: "relative",
              left: "0px",

              display: "inline"
            }} />

            <br></br>

            <h1 className={styles.title} style={{ display: "inline", color: "#ab529ba3", fontSize: "40px" }}>
              Me llamo
            </h1>
            <br></br>
            <h1 className={styles.title} style={{ display: "inline", fontSize: "40px" }}>
              {
                user.split('').map((letter, index) => {
                  return <p key={index} style={{ color: "#ab529ba3", display: "inline" }}>
                    {letter.toUpperCase()}
                  </p>
                })
              }
            </h1>

            <br></br>

            <img src="/t2/3.png" alt="me" width="200" style={{
              top: "0px!important",
              position: "relative",
              left: "0px",
              filter: "opacity(0.8)",
              display: "inline"
            }} />

            <br></br>

            <img src="/t2/2.png" alt="me" width="400" style={{
              top: "0px!important",
              position: "relative",
              left: "0px",
              filter: "opacity(0.8)",
              display: "inline"
            }} />
          </div>

          <center>
            <div className="row justify-content-md-center">
              <div className='col' style={{}} >
                <div className="col align-self-end col-6 col-sm-3" style={{ width: "100%" }}>
                  {dtnDonwload(handleDownloadImageFlayer, "full")}
                </div>
              </div>
              <div style={{}} ></div>
            </div>
          </center>



        </div>


        <center>
          <p>
            creditos desing:
            <br></br>
            https://www.facebook.com/PMUDLAPhoenix/
            <br></br>
            https://www.facebook.com/jhonnyer.galindez
            <br></br>
            https://www.facebook.com/jhonhemayr.concejalanimalista
            <br></br>

          </p>
        </center>


        <style jsx>{`


        input {
          border: 0;
          outline: 0;
          text-align: center;
          border: none!important;
        }
        input:focus {
          color: GRAY;
          outline:none!important;
          border: none!important;
        }

        .basic {
          text-align: center;
          
          font-family: "myFirstFont";
          font-weight: bolder;
          letter-spacing: -12px;
        }

        .basic2 {
          text-align: center;
          
          font-family: myFirstFont;
          font-weight: bolder;
          letter-spacing: -2px;
        }

        .inp {
          width: 100%;
          padding: 12px 20px;
          margin: 8px 0;
          box-sizing: border-box;
          border: none!important;
          border-bottom: 2px solid red!important;
        }

        .sombra {
          
          border-radius: 5px;
          -webkit-box-shadow: 0px 0px 20px -6px rgba(0,0,0,0.47)!important;
          -moz-box-shadow: 0px 0px 20px -6px rgba(0,0,0,0.47)!important;
          box-shadow: 0px 0px 20px -6px rgba(0,0,0,0.47)!important;
        }

        

        @font-face {
          font-family: myFirstFont;
          src: url(LMB.otf);
        }

      `}</style>
      </main>

      <footer className={styles.footer}>
        
        <a
          style={{ textDecoration: "none" }}
          href="https://www.facebook.com/victor.hurtadojaramillo"
          target="_blank"
          rel="noopener noreferrer"
        >
          <b>creditos develoment {'❤️'} Victor Hugo </b>
        </a>


        <a
          style={{ textDecoration: "none" }}
          href="https://www.facebook.com/Jordanminota/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <code> Los vientos del Cauca para toda Colombia. v0.1.2</code>
        </a>
      </footer>
    </div>
  )
}
